* Angular
** Modules
NgModule is a decorator function that takes a single metadata object whose properties describe the module.
- declarations - the view classes that belong to this module. Angular has three kinds of view classes: components, directives, and pipes.
- exports - the subset of declarations that should be visible and usable in the component templates of other modules.
- imports - other modules whose exported classes are needed by component templates declared in this module.
- providers - creators of services that this module contributes to the global collection of - services; they become accessible in all parts of the app.
- bootstrap - the main application view, called the root component, that hosts all other app views. Only the root module should set this bootstrap property.
** Data Binding
For Two-Way binding we need to include the FormsModule
Types:
- property: <img [src]="imgUrl" />
- event: <button (click)="onBtnClick">Click</button>
- two-way: <input [(ngModel)]="name" />
- attribute: <button [attr.aria-label]="help">Help</button>
- class: <div [class.special]="isSpecial">Special</div>
- style: <label [style.color]="color">Label</label>
